name = "jellyfin-worker"
main = "./jellyfin.js"
compatibility_date = "2022-10-09"
account_id = "25f21f141824546aa72c74451a11b419"

[dev]
port = 9001
local_protocol="http"
upstream_protocol="https"

[env.staging]
name = "staging-jellyfin"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-jellyfin"
vars = { ENVIRONMENT = "production" }
route = { pattern = "*jellyfin.erfianugrah.com/*", zone_id = "3f2c4daa43d5920f313654a873b31d06" }