name = "jellyfin-worker"
type = "javascript"

[env.staging]
name = "staging-jellyfin"
vars = { ENVIRONMENT = "staging" }
workers_dev = true

[env.prod]
name = "prod-jellyfin"
vars = { ENVIRONMENT = "production" }
route = "*jellyfin.erfianugrah.com/*"